### ISSUE TITLE
Love this!

### ISSUE THREAD

**Issue by jrmusan** [Taolanoz/MMM-RSS-FEED#1]
This rss feed has been the icing on finishing up this mirror!
Quick question, how can i go about making the text more bright so it will be easier to read? 
Thanks!! 
Cheers

**Comment by maxenxe** [comment]
I think that if you set the color of the text to white it must be good, so go to the css folder, open the style.css file and add "color: white;"
Now your style.css file should look something like this:

div { 
	font-size: 24px;
        color: white;
}

Nice to help you 😄 !

**Comment by jrmusan** [comment]
My man! Worked like a charm, keep up the good work.
Happy holidays
