### ISSUE TITLE
new content fetch

### ISSUE THREAD

**Issue by sainiaj** [Taolanoz/MMM-RSS-FEED#2]
Hi Taolanoz/MMM-RSS-FEED,

very good module works great how can i make it so it fetch new content every hour i am using it to display quotes  from https://www.quotesdaddy.com/feed'

{
            module: 'MMM-RSS-FEED',
            position: 'bottom_bar',
            config: {
            url: 'https://www.quotesdaddy.com/feed'
            }
         },

**Comment by maxenxe** [comment]
Hello, i've not implemented this option, but i think that you can just disable this module and enable it again every hours.

**Comment by sainiaj** [comment]
thanks that is helpfull, only if i know how to do it, not very good with linux

**Comment by maxenxe** [comment]
Replace the code from MMM-RSS-FEED.js to this, ans it should work:  


Module.register("MMM-RSS-FEED",{

	defaults: {
		url: ""
	},
	getScripts: function() {
		return ["modules/MMM-RSS-FEED/js/jquery-3.1.1.min.js","modules/MMM-RSS-FEED/js/feednami.js"];
	},
		getStyles: function() {
		return ["modules/MMM-RSS-FEED/css/style.css"];
	},
	start: function() {
		Log.info("Starting module: " + this.name);
	},

	getDom: function () {
		var wrapper = document.createElement("div");
    		var url = this.config.url;
                function Request () {
		      feednami.load(url,function(result){
			    if(result.error) {
				    console.log(result.error);
			    } else {
				    var entries = result.feed.entries;
				    for(var i = 0; i < entries.length; i++){
				    var entry = entries[i];
				    wrapper.innerHTML = entry.title;
				    }
			    }
		    });
		    return wrapper;
	    }
            setInterval(Request, 1000 * 60 * 60);
      }
});

**Comment by sainiaj** [comment]
Hi Taolanoz,

Thanks for the js. code the module is loading but not showing anything on screen, 
i changed the time internal to  setInterval(Request, 1000 * 1 * 1); but not luck is it working for you
and thanks once again in advance

**Comment by maxenxe** [comment]
Can you tell me if there's anything un the console ? Thanks you

**Comment by sainiaj** [comment]
No nothing is showing on the console I even enabled header but nothing is
showing up

**Comment by maxenxe** [comment]
Sorry but i can't help you now, i'll send you a working code tommorow, if i forgot, just repost a message on this issue

**Comment by sainiaj** [comment]
alright thanks not a problem

**Comment by sainiaj** [comment]
@Taolanoz  any luck with the code 👍

**Comment by maxenxe** [comment]
I'm sorry but MagicMirror doesn't seem to accept the setTimeout function, i don't know why, it's weird i tried another code and nothing work `Module.register("MMM-RSS-FEED",{

	defaults: {
		url: ""
	},
	getScripts: function() {
		return ["modules/MMM-RSS-FEED/js/jquery-3.1.1.min.js","modules/MMM-RSS-FEED/js/feednami.js"];
	},
		getStyles: function() {
		return ["modules/MMM-RSS-FEED/css/style.css"];
	},
	start: function() {
		Log.info("Starting module: " + this.name);
	},

	getDom: function () {
		var now = new Date();
		var delay = 60 * 60 * 1000; // 1 hour in msec
		var start = delay - (now.getMinutes() * 60 + now.getSeconds()) * 1000 + now.getMilliseconds();

		setTimeout(function doSomething() {
			var wrapper = document.createElement("div");
			var url = this.config.url;
			feednami.load(url,function(result){
				if(result.error) {
					console.log(result.error);
				} else {
					var entries = result.feed.entries;
					for(var i = 0; i < entries.length; i++){
						var entry = entries[i];
						wrapper.innerHTML = entry.title;
					}
				}
			});
   		setTimeout(doSomething, delay);
		}, start);
		return wrapper;
	}
});
`
this is not working too, sorry

**Comment by Tueti** [comment]
This is because the DOM isn't updated in your code. I don't know if this is still an issue, but I would suggest to set an interval in `start()` like

```
start: function() {
   var self = this;
   setInterval(function() {
      self.updateDom(); //this is a module method to trigger a DOM update
   }, (60 * 60 * 1000))
}
```

and then in `getDom()` you only fetch the new random quote and display it. This way the DOM will be updated and everything should be displayed - **please note:** I only copied the feednami-code from above and pasted it in the getDom function, I don't know whether the code actually works. This is just how you need to structure the code. Hope this helps:

```
getDom: function() {
   var wrapper = document.createElement("div");
   var url = this.config.url;
   feednami.load(url,function(result){
      if(result.error) {
         console.log(result.error);
      } else {
         var entries = result.feed.entries;
	 for(var i = 0; i < entries.length; i++){
            var entry = entries[i];
            wrapper.innerHTML = entry.title;
         }
      }
   }
   return wrapper;
}
```
