### ISSUE TITLE
Question: Is it possible to display multiple entries

### ISSUE THREAD

**Issue by marksev1** [Taolanoz/MMM-RSS-FEED#3]
For example I pack sensor values into a RSS feed, can I display multiple entries? Or if  rephrase one feed has multiple entries (multiple sensor values) inside will it display all the text?

**Comment by maxenxe** [comment]
Honestly, i don't know 😂, but you can try.
If you know a bit of JavaScript, you can code a fonction that change the value every x minutes / hours / ...

Thanks for you interrest tout this module
